//
//  HomeInterfaces.swift
//  readhub
//
//  Created by Steve Lemuel on 10/15/19.
//  Copyright (c) 2019 Steve Lemuel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxCocoa
import RxSwift
import UIKit

enum Home {
    struct ViewOutput {
    }

    struct ViewInput {
    }
}

protocol HomeWireframeInterface: WireframeInterface {
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func configure(with output: Home.ViewOutput) -> Home.ViewInput

    // MARK: Observables -

    var topicListObservable: Observable<TopicListModel> { get }
    var newsListObservable: Observable<NewsListModel> { get }
    var technewsListObservable: Observable<TechnewsListModel> { get }
    var blockchainListObservable: Observable<BlockchainListModel> { get }

    // MARK: Functions -

    func getTopicList()
    func getNewsList()
    func getTechnewsList()
    func getBlockchainList()
}

protocol HomeInteractorInterface: InteractorInterface {
    func getTopicList(lastCursor: String, pageSize: Int) -> Single<TopicListModel>

    func getNewsList(lastCursor: String, pageSize: Int) -> Single<NewsListModel>
    
    func getTechnewsList(lastCursor: String, pageSize: Int) -> Single<TechnewsListModel>
    
    func getBlockchainList(lastCursor: String, pageSize: Int) -> Single<BlockchainListModel>
}
