//
//  HomeViewController.swift
//  readhub
//
//  Created by Steve Lemuel on 10/15/19.
//  Copyright (c) 2019 Steve Lemuel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxCocoa
import RxSwift
import SnapKit
import Then
import TYPagerController
import UIKit

fileprivate struct Metric {
    static let pagerBarFont = UIFont.systemFont(ofSize: 18.0)
    static let pagerBarHeight: CGFloat = 40.0

    static let titleHeight: CGFloat = 50.0

    static let titleIconSize: CGFloat = 25.0
    static let titleIconMargin: CGFloat = 15.0
}

final class HomeViewController: BaseViewController {
    // MARK: - Public properties -

    var presenter: HomePresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    private var titleView: UIView!
    private var settingBtn: UIImageView!
    private var bookmarkBtn: UIButton!

    private let titles: [String] = ["热门话题", "科技动态", "开发者", "区块链"]
    private let pageVC = TYTabPagerController().then {
        $0.pagerController.scrollView?.backgroundColor = kThemePrimaryColor
        $0.pagerController.layout.prefetchItemCount = 3
        $0.tabBar.layout.cellWidth = kScreenW * 0.24
        $0.tabBar.layout.progressColor = kThemePrimaryColor
        $0.tabBar.layout.selectedTextColor = kThemePrimaryColor
        $0.tabBar.backgroundColor = kThemeBase2Color
        $0.tabBar.layout.cellSpacing = 0
        $0.tabBar.layout.cellEdging = 0
        $0.tabBar.layout.normalTextFont = Metric.pagerBarFont
        $0.tabBar.layout.selectedTextFont = Metric.pagerBarFont
        $0.tabBar.layout.adjustContentCellsCenter = true
        $0.tabBarHeight = Metric.pagerBarHeight
    }

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        configure()

        setupLayout()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupNavigationBar()
    }

    private func setupNavigationBar() {
        navigationController?.navigationBar.barTintColor = kThemeBase2Color
    }

    private func setupLayout() {
        setupTitleView()
        setupPageController()
    }

    private func setupTitleView() {
        let logo = UIBarButtonItem(title: "Readhub+", style: .plain, target: self, action: nil).then {
            let attributes = [
                NSAttributedString.Key.foregroundColor: kThemePrimaryColor,
                NSAttributedString.Key.font: UIFont.systemFont(ofSize: Metric.titleIconSize),
            ]
            $0.setTitleTextAttributes(attributes, for: .normal)
        }

        navigationItem.leftBarButtonItem = logo
    }

    private func setupPageController() {
        addChild(pageVC)
        view.addSubview(pageVC.view)

        pageVC.delegate = self
        pageVC.dataSource = self

        let pageView = pageVC.view

        pageView?.snp.makeConstraints { make in
            make.top.equalTo(view.safeAreaLayoutGuide.snp.top)
            make.left.right.equalToSuperview()
            make.bottom.equalTo(view.safeAreaLayoutGuide.snp.bottom)
        }

        // add shadow effect
        pageView?.layer.shadowColor = kThemeFontColor.cgColor
        pageView?.layer.shadowOpacity = 0.7
        pageView?.layer.shadowRadius = 5
        pageView?.layer.shadowOffset = CGSize(width: 10.0, height: 10.0)

        pageVC.reloadData()

        // 设置起始页
        pageVC.pagerController.scrollToController(at: 0, animate: false)
    }

    private func setRx() {
    }
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}

private extension HomeViewController {
    func configure() {
        let output = Home.ViewOutput()

        _ = presenter.configure(with: output)
    }
}

extension HomeViewController: TYTabPagerControllerDelegate, TYTabPagerControllerDataSource {
    func numberOfControllersInTabPagerController() -> Int {
        return titles.count
    }

    func tabPagerController(_ tabPagerController: TYTabPagerController, controllerFor index: Int, prefetching: Bool) -> UIViewController {
        if index == 0 {
            let VC = TopicViewController(presenter: presenter)
            VC.view.backgroundColor = kThemeBase2Color
            return VC
        } else if index == 1 {
            let VC = NewsViewController(newsType: .news, presenter: presenter)
            VC.view.backgroundColor = kThemeBase2Color
            return VC
        } else if index == 2 {
            let VC = NewsViewController(newsType: .technews, presenter: presenter)
            VC.view.backgroundColor = kThemeBase2Color
            return VC
        } else if index == 3 {
            let VC = NewsViewController(newsType: .blockchain, presenter: presenter)
            VC.view.backgroundColor = kThemeBase2Color
            return VC
        }

        let VC = UIViewController()
        VC.view.backgroundColor = kThemeBase2Color
        return VC
    }

    func tabPagerController(_ tabPagerController: TYTabPagerController, titleFor index: Int) -> String {
        return titles[index]
    }
}
