//
//  SettingsPresenter.swift
//  readhub
//
//  Created by Steve Lemuel on 11/8/19.
//  Copyright (c) 2019 Steve Lemuel. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class SettingsPresenter {

    // MARK: - Private properties -

    private unowned let view: SettingsViewInterface
    private let wireframe: SettingsWireframeInterface

    // MARK: - Lifecycle -

    init(view: SettingsViewInterface, wireframe: SettingsWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension SettingsPresenter: SettingsPresenterInterface {

    func configure(with output: Settings.ViewOutput) -> Settings.ViewInput {
        return Settings.ViewInput()
    }

}
